core/urls.py
# core = DjangoLearning
"""
URL configuration for djangoLearning project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('interactome/', include('interactome.urls')),
    path('admin/', admin.site.urls),
]

interactome/urls.py
# Author: Lunelys RUNESHAW <lunelys.runeshaw@etudiant.univ-rennes.fr>
# URL configuration for interactome project

from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'interactome'
urlpatterns = [
                  path('', views.index, name='index'),
                  path('search/', views.search, name='search'),
                  path('archive/', views.archive, name="archive"),
                  path('about/', views.about, name='about'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# https://docs.djangoproject.com/en/4.2/howto/static-files/#deployment

interactome/models.py
from django.db import models
from django.utils.translation import gettext as _
from datetime import datetime


class Prot(models.Model):
    id = models.CharField(max_length=255, primary_key=True, unique=True)
    prot1 = models.CharField(_("prot1"), max_length=25, default='-')
    prot2 = models.CharField(_("prot2"), max_length=25, default='-')
    gene1 = models.CharField(_("gene1"), max_length=40, default='-')
    gene2 = models.CharField(_("gene2"), max_length=40, default='-')
    idm = models.CharField(_("idm"), max_length=255, default='-')
    authors = models.CharField(_("authors"), max_length=255, default='-')
    pub_id = models.CharField(_("pub_id"), max_length=25, default='-')
    species1 = models.CharField(_("species1"), max_length=40, default='-')
    species2 = models.CharField(_("species2"), max_length=40, default='-')
    interaction_type = models.CharField(_("interaction_type"), max_length=255, default='-')
    source_databases = models.CharField(_("source_databases"), max_length=150, default='-')
    interaction_identifiers = models.CharField(_("interaction_identifiers"), max_length=150, default='-')
    confidence_score = models.CharField(_("confidence_score"), max_length=150, default='-')
    biological_role1 = models.CharField(_("biological_role1"), max_length=255, default='-')
    biological_role2 = models.CharField(_("biological_role2"), max_length=255, default='-')
    exp_role1 = models.CharField(_("exp_role1"), max_length=255, default='-')
    exp_role2 = models.CharField(_("exp_role2"), max_length=255, default='-')
    interactor_type1 = models.CharField(_("interactor_type1"), max_length=255, default='-')
    interactor_type2 = models.CharField(_("interactor_type2"), max_length=255, default='-')
    taxid_host = models.CharField(_("taxid_host"), max_length=100, default='-')
    participant_id_method1 = models.CharField(_("participant_id_method1"), max_length=255, default='-')
    participant_id_method2 = models.CharField(_("participant_id_method2"), max_length=255, default='-')
    service_name = models.CharField(_("service_name"), max_length=100, default='-')
    biogrid_experimental_system = models.CharField(_("biogrid_experimental_system"), max_length=100, default='-')
    biogrid_description = models.CharField(_("biogrid_description"), max_length=400, default='-')
    biogrid_type = models.CharField(_("biogrid_type"), max_length=50, default='-')
    throughput = models.CharField(_("throughput"), max_length=100, default='-')
    count_impl = models.PositiveSmallIntegerField("count_impl", default='0')
    csv_file_taxid = models.PositiveIntegerField("csv_file_taxid", default='0')
    csv_file_date = models.DateField("csv_file_date", default=datetime.now().strftime('%Y-%m-%d'))
    onlyMIs = models.JSONField("onlyMIs", default=list)

    # class Meta:
    #     unique_together = ('prot1', 'prot2', 'pubid')
    # from functools import reduce
    # import operator
    # from django.db.models import Q
    #
    # Prot.objects.filter(reduce(operator.and_, (Q(first_name__contains=x) for x in ['x', 'y', 'z'])))

interactome/views.py
# Author: Lunelys RUNESHAW <lunelys.runeshaw@etudiant.univ-rennes.fr>
#
# archive view: put in folder /media the files you want to appear in the archive page
# when switching from test version to real version, you'll have to switch from SQLite to mySQL
# TODO: change DB to mySQL -> https://docs.djangoproject.com/en/4.2/intro/tutorial02/

import os
import pandas as pd
import json
from datetime import datetime
from django.http import HttpResponse, FileResponse
from django.shortcuts import render
from django.conf import settings
from django.db.models import Q
from .models import Prot


# This is the index/home page, displaying mainly the search bar
def index(request):
    taxids_in_db = Prot.objects.all().values('csv_file_taxid').distinct()
    in_db = []
    for index, taxid_in_db in enumerate(taxids_in_db):
        taxid_date = Prot.objects.filter(Q(csv_file_taxid=taxid_in_db['csv_file_taxid'])).values('csv_file_date')[0][
            'csv_file_date']
        in_db_dict = {'taxid_in_db': taxid_in_db['csv_file_taxid'],
                      'date_in_db': taxid_date}
        in_db.append(in_db_dict)
    return render(request, 'interactome/index.html', {'in_db': in_db, })


# This is the page that appears when a user search for an interaction, displaying the data as tables from the database
def search(request):
    if request.GET:
        query = request.GET.get('search')
        results = Prot.objects.filter(
            Q(prot1__iexact=query) | Q(prot2__iexact=query) | Q(gene1__iexact=query) | Q(gene2__iexact=query))
        if results.exists():
            df = pd.DataFrame(list(results.values()))
            df = df.drop('onlyMIs', axis=1)
            df[['prot1', 'prot2']] = df[['prot2', 'prot1']] \
                .where(((df['prot2'].str.upper() == query.upper()) | (df['gene2'].str.upper() == query.upper())),
                       df[['prot1', 'prot2']].values)
            df[['gene1', 'gene2']] = df[['gene2', 'gene1']] \
                .where(((df['prot2'].str.upper() == query.upper()) | (df['gene2'].str.upper() == query.upper())),
                       df[['gene1', 'gene2']].values)
            df[['species1', 'species2']] = df[['species2', 'species1']] \
                .where(((df['prot2'].str.upper() == query.upper()) | (df['gene2'].str.upper() == query.upper())),
                       df[['species1', 'species2']].values)
            df[['biological_role1', 'biological_role2']] = df[['biological_role2', 'biological_role1']] \
                .where(((df['prot2'].str.upper() == query.upper()) | (df['gene2'].str.upper() == query.upper())),
                       df[['biological_role1', 'biological_role2']].values)
            df[['exp_role1', 'exp_role2']] = df[['exp_role2', 'exp_role1']] \
                .where(((df['prot2'].str.upper() == query.upper()) | (df['gene2'].str.upper() == query.upper())),
                       df[['exp_role1', 'exp_role2']].values)
            df[['interactor_type1', 'interactor_type2']] = df[['interactor_type2', 'interactor_type1']] \
                .where(((df['prot2'].str.upper() == query.upper()) | (df['gene2'].str.upper() == query.upper())),
                       df[['interactor_type1', 'interactor_type2']].values)
            df[['participant_id_method1', 'participant_id_method2']] = df[
                ['participant_id_method2', 'participant_id_method1']] \
                .where(((df['prot2'].str.upper() == query.upper()) | (df['gene2'].str.upper() == query.upper())),
                       df[['participant_id_method1', 'participant_id_method2']].values)
            df['Count'] = df.groupby(['prot2'])['id'].transform('count')
            df = df.drop_duplicates()
            df = df.sort_values(by=['Count']).reset_index(drop=True)

            checked = ""
            if request.method == "POST":
                if request.POST.get('reproducible') == "True":
                    df = df[df.Count >= 2]
                    checked = "checked"

            result = df.to_json(orient="index")
            parsed = json.loads(result)

            if request.GET.get('format') == 'csv':
                response = HttpResponse(content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename=interactors_' + query + '.csv'
                if request.GET.get('checked') == "checked":
                    df = df[df.Count >= 2]
                df = df.drop(columns=['id', 'Count', 'onlyMIs'])
                df.to_csv(response, encoding='utf-8', index=False, )
                return response

            return render(request, 'interactome/search.html',
                          {'data': parsed.values(), 'query': query, 'checked': checked, })

        else:
            error_message = 'No results for "' + query + '". Try another protein or check for any spelling error.'
            return render(request, 'interactome/index.html', {'error_message': error_message, })


# This is the page that appears when a user click on "archive" in the navbar, displaying previous files to download
def archive(request):
    now = datetime.now().strftime('%Y-%m-%d')
    current_filename = 'reproducible_interactome_all_latest_' + now + '.csv'
    files = []
    for item in os.scandir(settings.MEDIA_ROOT):
        temp_dict = {
            'name': item.name,
            'modified': datetime.fromtimestamp(item.stat().st_mtime).strftime('%d-%m-%Y'),
            'size': f"{item.stat().st_size / (1 << 17):,.0f}MB"
        }
        files.append(temp_dict)

    if request.GET.get('format') == 'csv':
        path_file = os.path.join(settings.MEDIA_ROOT, request.GET.get('search'))
        file = open(path_file, 'rb')
        response = FileResponse(file, as_attachment=True)
        return response
    elif request.GET.get('current') == 'current':
        results = Prot.objects.all()
        df = pd.DataFrame(list(results.values()))
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename=' + current_filename
        df = df.drop(columns=['id'])
        df.to_csv(response, encoding='utf-8', index=False, )
        return response
    return render(request, 'interactome/archive.html', {'total_files': files,
                                                        'path': settings.MEDIA_ROOT,
                                                        'filename': current_filename, })


# This is the page that appears when a user click on "about" in the navbar, displaying basic info about the project
def about(request):
    return render(request, 'interactome/about.html')


# not used for the moment: maybe to add later, for a better tooltip function
definitions = {
    "Affinity Capture-Luminescence": "An interaction is inferred when a bait protein, tagged with luciferase, is enzymatically detected in immunoprecipitates of the prey protein as light emission. The prey protein is affinity captured from cell extracts by either polyclonal antibody or epitope tag.",
    "Affinity Capture-MS": "The bait protein is affinity captured from cell extracts by either polyclonal antibody or epitope tag and the associated interaction partner is identified by MS methods.",
    "Affinity Capture-RNA": "An interaction is inferred when a 'bait' protein is affinity captured from cell extracts by either polyclonal antibody or epitope tag and the associated interaction partner is an RNA molecule.",
    "Affinity Capture-Western": "The bait protein is affinity captured from cell extracts by either polyclonal antibody or epitope tag and the associated interaction partner is identified by western blot with a specific polyclonal antibody or a second epitope tag. This category is also used if an interacting protein was visualized directly by dye stain or radioactivity.",
    "Biochemical Activity": "Interaction is inferred from a biochemical effect of one protein upon another, for example, GTP-GDP exchange activity or phosphorylation of a substrate by a kinase.",
    "Co-crystal Structure": "Interaction is directly demonstrated at the atomic level by X-ray crystallography.",
    "Co-fractionation": "Interaction is inferred from the presence of two or more protein subunits in a partially purified protein preparation.",
    "Co-localization": "Interaction is inferred from two proteins that co-localize in the cell by indirect immunofluorescence, usually in a co-dependent manner. This category also includes co-dependent association of proteins with promoter DNA in chromatin immunoprecipitation experiments.",
    "Co-purification": "Interaction is inferred from the identification of two or more protein subunits in a purified protein complex, as obtained by classical biochemical fractionation or by affinity purification and one or more additional fractionation steps.",
    "Far Western": "Interaction is detected between a protein immobilized on a membrane and a purified protein probe.",
    "FRET": "The close proximity of interaction partners is detected by fluorescence resonance energy transfer (FRET) between cyan fusion protein (CFP) and yellow fluorescent protein (YFP) fusion proteins in vivo.",
    "PCA": "A protein-protein interaction assay in which a bait protein is expressed as fusion to one of the either N- or C- terminal peptide fragments of a reporter protein and prey protein is expressed as fusion to the complementary N- or C- terminal fragment of the same reporter protein. Interaction of bait and prey proteins bring together complementary fragments, which can then fold into an active reporter.",
    "Protein-peptide": "Interaction is detected between a protein and a peptide derived from an interaction partner. This category includes phage-display experiments.",

templates/interactome/about.html
{# Author: Lunelys RUNESHAW <lunelys.runeshaw@etudiant.univ-rennes.fr>#}
{#This is the page that appears when a user click on "about" in the navbar, displaying basic info about the project #}

<html lang="en">
<head>
    <title>reproducible-interactome</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js/"></script>
</head>

<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark border-bottom border-bottom-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'interactome:index' %}">reproducible-interactome v2.0 (MOCKUP)</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">Versions</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" target="_blank"
                               href="https://reproducible-interactome.genouest.org/about">v1.0</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'interactome:index' %}">v2.0</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interactome:archive' %}">Archive</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interactome:about' %}">About</a>
                </li>
            </ul>
            <form class="d-flex mb-0" role="search" action="{% url 'interactome:search' %}" method="get">
                {% csrf_token %}
                <input type="search" name="search" id="search" required minlength="3" maxlength="10"
                       placeholder="Search" autocomplete="off" spellcheck="false" class="form-control">
            </form>
        </div>
    </div>
</nav>

<div class="position-absolute top-50 start-50 w-50 translate-middle text-center d-flex p-3 mx-auto flex-column">
    <main class="px-3">
        <p class="lead fs-4">This interface enables to search experimental evidences for different species interactions.
            These experimental
            evidences have been curated from both explicit and implicit redundancies, as described in <a
                    class="text-decoration-none"
                    href="https://pubmed.ncbi.nlm.nih.gov/35015827/">Melkonian et al.</a></p>
        <br>
        <p class="lead fs-4">The reproducible-interactome v2.0 was coded by Lunelys Runeshaw during a 2 months first
            year of a master's degree internship, with Gwenael Rabut as supervisor.</p>
        <br>
        <p class="lead">This web interface has been developed by: Lunelys Runeshaw. This is the mockup version of
            the website, with only a few NAM7 interactions in the database, to show the functionalities.</p>
        <br> <br>
        <p class="lead">All tools used are available on <a class="text-decoration-none"
                                                           href="https://github.com/lunelys/reproducible-interactome-v2.0/">GitHub</a>.
        </p>
    </main>
</div>


</body>
</html>

{#<p>The curation process relies on Semantic Web technologies and has been designed by:</p>#}
{#<ul>#}
{#    <li> Marc Melkonian<sup>1,2</sup>,</li>#}
{#    <li> Camille Juigné<sup>1,3</sup>,</li>#}
{#    <li> Olivier Dameron<sup>1</sup>,</li>#}
{#    <li> Gwenaël Rabut<sup>2</sup>,</li>#}
{#    <li> Emmanuelle Becker<sup>1</sup>,</li>#}
{#</ul>#}


{#<br>#}

{#<ul>#}
{#    <li><sup>[1]</sup> Univ Rennes, Inria, CNRS, IRISA, F-35000, Rennes, France</li>#}
{#    <li><sup>[2]</sup> Univ Rennes, CNRS, IGDR - UMR 6290, F-35000, Rennes, France</li>#}
{#    <li><sup>[3]</sup> Pegase, Inrae, Institut Agro, 35590 Saint-Gilles, France.</li>#}
{#</ul>#}

templates/interactome/archive.html
{# Author: Lunelys RUNESHAW <lunelys.runeshaw@etudiant.univ-rennes.fr>#}
{#This is the page that appears when a user click on "archive" in the navbar, displaying previous files to download #}

{% load static %}
<html lang="en">
<head>
    <title>reproducible-interactome</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js/"></script>
</head>

<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark border-bottom border-bottom-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'interactome:index' %}">reproducible-interactome v2.0 (MOCKUP)</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">Versions</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" target="_blank" href="https://reproducible-interactome.genouest.org/about">v1.0</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'interactome:index' %}">v2.0</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interactome:archive' %}">Archive</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interactome:about' %}">About</a>
                </li>
            </ul>
            <form class="d-flex mb-0" role="search" action="{% url 'interactome:search' %}" method="get">
                {% csrf_token %}
                <input type="search" name="search" id="search" required minlength="3" maxlength="10"
                       placeholder="Search" autocomplete="off" spellcheck="false" class="form-control">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid mx-auto flex-column w-75">
    <main>
        <h1 class="text-center py-4">You can download here previous and current dataset</h1>
        <br>
        <form class="text-center" method='GET'>
            {% csrf_token %}
            <input type='hidden' name='current' value='current'>
            <input type="submit" value="Download current dataset (all species)" class="btn btn-success btn-lg">
        </form>
        <br>
        <ul class="list-group">
            {% for file in total_files %}
                <form method='GET'>
                    {% csrf_token %}
                    <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                        <input type='hidden' name='format' value='csv'>
                        <input type='hidden' name='search' value={{ file.name }}>
                        <input type="submit" value="{{ file.name }}"
                               class="btn btn-link text-decoration-none">
                        <div class="d-flex">
                            <span class="badge bg-secondary rounded-pill">Size: {{ file.size }}</span>
                            <span class="badge bg-info rounded-pill ms-2">Modified on: {{ file.modified }}</span>
                        </div>
                    </li>
                </form>
            {% endfor %}
        </ul>
    </main>
</div>


</body>
</html>

templates/interactome/index.html
{# Author: Lunelys RUNESHAW <lunelys.runeshaw@etudiant.univ-rennes.fr>#}
{#This is the index/home page, displaying mainly the search bar#}

{#{% load static %}#}

<html lang="en">
<head>
    <title>reproducible-interactome</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark border-bottom border-bottom-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'interactome:index' %}">reproducible-interactome v2.0 (MOCKUP)</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">Versions</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" target="_blank"
                               href="https://reproducible-interactome.genouest.org/about">v1.0</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'interactome:index' %}">v2.0</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interactome:archive' %}">Archive</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interactome:about' %}">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="position-relative mt-5 me-3">
    <div class="card position-absolute top-0 end-0" style="width: 18rem;">
        <div class="card-header text-center">
            Species currently in database
        </div>
        <ul class="list-group list-group-flush">
            {% for dict in in_db %}
                <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                    {{ dict.taxid_in_db }}
                    <div class="d-flex">
                        <span class="badge bg-info rounded-pill ms-2">Modified on: {{ dict.date_in_db }}</span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="position-absolute top-50 start-50 w-25 translate-middle text-center">
    <form action="{% url 'interactome:search' %}" method="get">
        {% csrf_token %}
        <h1 class="h1 mb-1 fw-normal">Search interactions</h1>
        <p class="lead pb-2 fw-light">Enter a primary accession identifier or gene name</p>
        {% if error_message %}<p class="text-danger lead"><strong>{{ error_message }}</strong></p>{% endif %}
        <div class="row">
            <div class="col-sm-9">
                <fieldset>
                    <input type="text" name="search" id="search" required minlength="3" maxlength="10"
                           placeholder="P30771 or NAM7" autocomplete="off" spellcheck="false" class="form-control">
                </fieldset>
            </div>
            <div class="col-sm-3">
                <input type="submit" value="Search" class="btn btn-dark">
            </div>
        </div>
    </form>
</div>

</body>
</html>